compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
  cpu:
    - arm64
    - x64
  os:
    - darwin
    - linux
  libc:
    - gnu
    - glibc

yarnPath: .yarn/releases/yarn-4.4.0.cjs
